# Prediction

In [1]:
import warnings
warnings.filterwarnings('ignore')


import pandas as pd
import numpy as np
from plotnine import *

import statsmodels.api as sm


from sklearn.linear_model import LogisticRegression # Logistic Regression Model
from sklearn.preprocessing import StandardScaler #Z-score variables
from sklearn.metrics import accuracy_score, confusion_matrix

from sklearn.model_selection import train_test_split # simple TT split cv
from sklearn.model_selection import KFold # k-fold cv
from sklearn.model_selection import LeaveOneOut #LOO cv
from sklearn.model_selection import cross_val_score # cross validation metrics
from sklearn.model_selection import cross_val_predict # cross validation metrics

## Framework
1. Model
2. Fit
3. Predict

In [2]:
# data
fashionBIG = pd.read_csv("https://raw.githubusercontent.com/cmparlettpelleriti/CPSC392ParlettPelleriti/master/Data/SKP_fashionBIG.csv")
fashionBIG.head()

age  income  months_subbed  upgrade
0   22   55.89             14        0
1   32   86.03             57        0
2   38   49.22             37        1
3   14   92.71             51        1
4   33   94.06             37        0

In [3]:
predictors = ["age", "income", "months_subbed"]


In [4]:
#create

In [5]:
 #fit

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='none',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
 #predict

In [7]:
# acc

0.535

In [8]:
# confusion matrix

array([[21, 66],
       [27, 86]])

## Predict New Data

In [9]:
fashionNEW = pd.read_csv("https://raw.githubusercontent.com/cmparlettpelleriti/CPSC392ParlettPelleriti/master/Data/SKP_fashionNEW.csv")



array([1, 0, 1, 1, 1, 1, 1, 1, 0])

0.591

array([[103, 294],
       [115, 488]])

## LR different thresholds


array([[0.33156321, 0.66843679],
       [0.51003902, 0.48996098],
       [0.46760441, 0.53239559],
       [0.37223864, 0.62776136],
       [0.43324913, 0.56675087],
       [0.49607398, 0.50392602],
       [0.42802762, 0.57197238],
       [0.32762291, 0.67237709],
       [0.58588873, 0.41411127]])

array([0.66843679, 0.48996098, 0.53239559, 0.62776136, 0.56675087,
       0.50392602, 0.57197238, 0.67237709, 0.41411127, 0.60231831,
       0.60437006, 0.33669794, 0.52155406, 0.50946063, 0.49259906,
       0.37580112, 0.56126836, 0.76527856, 0.61314534, 0.53630122,
       0.58746315, 0.63097807, 0.61215181, 0.38639761, 0.67675288,
       0.56903559, 0.55507461, 0.62111378, 0.53722139, 0.53811983,
       0.4862273 , 0.43709781, 0.57439125, 0.45757176, 0.36402141,
       0.77506185, 0.68377377, 0.59467102, 0.35830067, 0.55287177,
       0.71946175, 0.5550516 , 0.75899002, 0.54263392, 0.59799537,
       0.57869673, 0.69449914, 0.65028929, 0.59435488, 0.56395212,
       0.62922188, 0.68207844, 0.6565115 , 0.60561746, 0.43065165,
       0.54726567, 0.70574548, 0.6361744 , 0.54289912, 0.59366407,
       0.72113109, 0.56777977, 0.65235698, 0.52142422, 0.62420478,
       0.7027454 , 0.65267477, 0.76835568, 0.6133941 , 0.51036317,
       0.72366211, 0.32908061, 0.44155303, 0.41846511, 0.73654

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

0.602

## LR with Cross Validation

In [ ]:
# Kfold



# create k-fold object

 #create model

#create empty list to store accuracy for each fold

In [ ]:
# Use a for loop to loop through each fold and train a model, then add the accuracy to acc.

for train_indices, test_indices in kf.split(X):
    # Get your train/test for this fold

    
    # model

    # record accuracy

    
#print overall acc


## Regularization

In [ ]:
# Default Regularization
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

#create
# myLogit = LogisticRegression(penalty = "none") #create
#fit

