In [1]:
import pandas as pd
import numpy as np

# Creating a DF

In [2]:
# Make my own DF
Name = ["Tom", "Jane", "Alice"]
Age = [20, 21, 19]
Major = ["Business", "Data Analytics", "Business"]

toDF = {"Name": Name, "Age": Age, "Major": Major}

DF = pd.DataFrame(toDF)

DF.head()


Name  Age           Major
0    Tom   20        Business
1   Jane   21  Data Analytics
2  Alice   19        Business

In [4]:
# With Lists
toDF2 = [["Tom", 20, "Business"], ["Jane", 21, "Data Analytics"], ["Alice", 19, "Business"]]

DF2 = pd.DataFrame(toDF2, columns = ["Name", "Age", "Major"])

DF2.head()

Name  Age           Major
0    Tom   20        Business
1   Jane   21  Data Analytics
2  Alice   19        Business

In [5]:
# From your Computer
pathDF = "/Users/chelseaparlett/Desktop/Desktop/School/CPSC392parlettpelleriti/Data/penguins.csv"

DF3 = pd.read_csv(pathDF)

DF3.head()

Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0           0  Adelie  Torgersen            39.1           18.7   
1           1  Adelie  Torgersen            39.5           17.4   
2           2  Adelie  Torgersen            40.3           18.0   
3           3  Adelie  Torgersen             NaN            NaN   
4           4  Adelie  Torgersen            36.7           19.3   

   flipper_length_mm  body_mass_g     sex  year  
0              181.0       3750.0    male  2007  
1              186.0       3800.0  female  2007  
2              195.0       3250.0  female  2007  
3                NaN          NaN     NaN  2007  
4              193.0       3450.0  female  2007

In [6]:
# From URL
urlDF = "https://raw.githubusercontent.com/cmparlettpelleriti/CPSC392ParlettPelleriti/master/Data/penguins.csv"

DF4 = pd.read_csv(urlDF)

DF4.head()


Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0           0  Adelie  Torgersen            39.1           18.7   
1           1  Adelie  Torgersen            39.5           17.4   
2           2  Adelie  Torgersen            40.3           18.0   
3           3  Adelie  Torgersen             NaN            NaN   
4           4  Adelie  Torgersen            36.7           19.3   

   flipper_length_mm  body_mass_g     sex  year  
0              181.0       3750.0    male  2007  
1              186.0       3800.0  female  2007  
2              195.0       3250.0  female  2007  
3                NaN          NaN     NaN  2007  
4              193.0       3450.0  female  2007

In [ ]:
# On Google Colab
DF5 = pd.read_csv("penguins.csv")
DF5.head()

# Exploring your DF

In [7]:
# Checking out your DF
DF4.shape

(344, 9)

In [8]:
# Column names
DF4.columns

Index(['Unnamed: 0', 'species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='object')

In [10]:
# What do your columns look like?
DF4.info()
DF4.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object 
 8   year               344 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB


Unnamed: 0  bill_length_mm  bill_depth_mm  flipper_length_mm  \
count  344.000000      342.000000     342.000000         342.000000   
mean    62.151163       43.921930      17.151170         200.915205   
std     40.430199        5.459584       1.974793          14.061714   
min      0.000000       32.100000      13.100000         172.000000   
25%     28.000000       39.225000      15.600000         190.000000   
50%     57.000000       44.450000      17.300000         197.000000   
75%     94.250000       48.500000      18.700000         213.000000   
max    151.000000       59.600000      21.500000         231.000000   

       body_mass_g         year  
count   342.000000   344.000000  
mean   4201.754386  2008.029070  
std     801.954536     0.818356  
min    2700.000000  2007.000000  
25%    3550.000000  2007.000000  
50%    4050.000000  2008.000000  
75%    4750.000000  2009.000000  
max    6300.000000  2009.000000

In [11]:
# head, 12
DF4.head(12)

Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0            0  Adelie  Torgersen            39.1           18.7   
1            1  Adelie  Torgersen            39.5           17.4   
2            2  Adelie  Torgersen            40.3           18.0   
3            3  Adelie  Torgersen             NaN            NaN   
4            4  Adelie  Torgersen            36.7           19.3   
5            5  Adelie  Torgersen            39.3           20.6   
6            6  Adelie  Torgersen            38.9           17.8   
7            7  Adelie  Torgersen            39.2           19.6   
8            8  Adelie  Torgersen            34.1           18.1   
9            9  Adelie  Torgersen            42.0           20.2   
10          10  Adelie  Torgersen            37.8           17.1   
11          11  Adelie  Torgersen            37.8           17.3   

    flipper_length_mm  body_mass_g     sex  year  
0               181.0       3750.0    male  2007  
1               186.0       3800.0  female  2007  
2               195.0       3250.0  female  2007  
3                 NaN          NaN     NaN  2007  
4               193.0       3450.0  female  2007  
5               190.0       3650.0    male  2007  
6               181.0       3625.0  female  2007  
7               195.0       4675.0    male  2007  
8               193.0       3475.0     NaN  2007  
9               190.0       4250.0     NaN  2007  
10              186.0       3300.0     NaN  2007  
11              180.0       3700.0     NaN  2007

## groupby()

In [16]:
# use groupby to get species average bill length
DF4.groupby(["species"])[["bill_length_mm", "bill_depth_mm"]].mean()

bill_length_mm  bill_depth_mm
species                                 
Adelie          38.791391      18.346358
Chinstrap       48.833824      18.420588
Gentoo          47.504878      14.982114

## index


In [ ]:
# index
DF4.index

In [ ]:
# looping through indices
for i in DF4.index:
    print(DF4[i])


In [ ]:
# iterrows
for i, r in DF4.iterrows():
    print(i,r)

## Dropping Missing Data

In [19]:
# Check for missing values
DF4.isnull().sum()

Unnamed: 0            0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [20]:
DF4 = DF4.dropna()
DF4.isnull().sum()

Unnamed: 0           0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [21]:
# another way to drop your data
DF4.dropna(inplace = True)

# inplace = don't make a copy, drop = don't add the indices as a column to your df
DF4.reset_index(inplace = True, drop = True)

## Creating Dummy Variables
### A single dummy variable

In [22]:
# simulate data
np.random.seed(8675309)

n = 100
x1 = np.random.choice(["A", "B", "C"], n)
x2 = np.random.normal(0,1,n)

df = pd.DataFrame({"group":x1, "happiness": x2})

df.head()

group  happiness
0     B  -0.998062
1     A   1.152839
2     A   0.193641
3     A   0.356045
4     A  -1.046417

In [23]:
# notice that the categorical variable `group`, has more than 2 categories.
dummies = pd.get_dummies(df, columns = ["group"])

# many algorithms want dummy/binary variables, so let's turn `group` into dummy/binary variables!

# you can see that we now have 3 columns, A, B, and C that
# are all binary variables indicating whether each person was
# A (1-yes, 0-no), B (1-yes, 0-no), or C (1-yes, 0-no)
dummies

happiness  group_A  group_B  group_C
0   -0.998062        0        1        0
1    1.152839        1        0        0
2    0.193641        1        0        0
3    0.356045        1        0        0
4   -1.046417        1        0        0
..        ...      ...      ...      ...
95   0.251880        0        1        0
96  -0.940828        0        0        1
97   1.012550        0        1        0
98   0.778642        0        1        0
99  -2.165909        1        0        0

[100 rows x 4 columns]

### Multiple dummy variables

In [24]:
np.random.seed(8675309)

n = 100
letter_grade = np.random.choice(["A", "B", "C", "D", "F"], n)
class_level = np.random.choice(["Freshman", "Sophomore", "Junior", "Senior"], n)
x2 = np.random.normal(0,1,n)

df = pd.DataFrame({"Grade":letter_grade, "Class": class_level, "happiness": x2})

df.head()

Grade      Class  happiness
0     B  Sophomore   0.629483
1     F   Freshman   2.109350
2     F   Freshman  -1.292751
3     A  Sophomore  -0.020285
4     A     Senior   0.735859

In [25]:
df = pd.get_dummies(df, columns = ["Grade", "Class"], drop_first = True)

df.head()

happiness  Grade_A  Grade_B  Grade_C  Grade_D  Grade_F  Class_Freshman  \
0   0.629483        0        1        0        0        0               0   
1   2.109350        0        0        0        0        1               1   
2  -1.292751        0        0        0        0        1               1   
3  -0.020285        1        0        0        0        0               0   
4   0.735859        1        0        0        0        0               0   

   Class_Junior  Class_Senior  Class_Sophomore  
0             0             0                1  
1             0             0                0  
2             0             0                0  
3             0             0                1  
4             0             1                0

# Grabbing Subsets of Data

## By Column Name

In [26]:
# Pulling certain rows/columns/sets
DF4["species"]

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...    
328    Chinstrap
329    Chinstrap
330    Chinstrap
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: object

In [28]:
DF4["bill_length_mm"].mean()

43.9927927927928

## By Index

In [29]:
DF4.iloc[8]

index                       13
Unnamed: 0                  13
species                 Adelie
island               Torgersen
bill_length_mm            38.6
bill_depth_mm             21.2
flipper_length_mm          191
body_mass_g               3800
sex                       male
year                      2007
Name: 8, dtype: object

In [30]:
#9th row
DF4.iloc[[8]]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
8     13          13  Adelie  Torgersen            38.6           21.2   

   flipper_length_mm  body_mass_g   sex  year  
8              191.0       3800.0  male  2007

In [31]:
#2-7 row
DF4.iloc[2:7]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
2      2           2  Adelie  Torgersen            40.3           18.0   
3      4           4  Adelie  Torgersen            36.7           19.3   
4      5           5  Adelie  Torgersen            39.3           20.6   
5      6           6  Adelie  Torgersen            38.9           17.8   
6      7           7  Adelie  Torgersen            39.2           19.6   

   flipper_length_mm  body_mass_g     sex  year  
2              195.0       3250.0  female  2007  
3              193.0       3450.0  female  2007  
4              190.0       3650.0    male  2007  
5              181.0       3625.0  female  2007  
6              195.0       4675.0    male  2007

In [32]:
#2-7 row
DF4.iloc[2:7,2:4]

species     island
2  Adelie  Torgersen
3  Adelie  Torgersen
4  Adelie  Torgersen
5  Adelie  Torgersen
6  Adelie  Torgersen

## By Condition (Booleans)

In [38]:
# Torgersen Penguins
# torg = DF4["island"] == "Torgersen"

# DF4.loc[torg].head()

adel = DF4["species"] == "Adelie"

DF4.loc[adel]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0        0           0  Adelie  Torgersen            39.1           18.7   
1        1           1  Adelie  Torgersen            39.5           17.4   
2        2           2  Adelie  Torgersen            40.3           18.0   
3        4           4  Adelie  Torgersen            36.7           19.3   
4        5           5  Adelie  Torgersen            39.3           20.6   
..     ...         ...     ...        ...             ...            ...   
141    147         147  Adelie      Dream            36.6           18.4   
142    148         148  Adelie      Dream            36.0           17.8   
143    149         149  Adelie      Dream            37.8           18.1   
144    150         150  Adelie      Dream            36.0           17.1   
145    151         151  Adelie      Dream            41.5           18.5   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
3                193.0       3450.0  female  2007  
4                190.0       3650.0    male  2007  
..                 ...          ...     ...   ...  
141              184.0       3475.0  female  2009  
142              195.0       3450.0  female  2009  
143              193.0       3750.0    male  2009  
144              187.0       3700.0  female  2009  
145              201.0       4000.0    male  2009  

[146 rows x 10 columns]

In [41]:
# bill length less than 39
shortboi = DF4["bill_length_mm"] < 39

DF4.loc[shortboi]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
3        4           4  Adelie  Torgersen            36.7           19.3   
5        6           6  Adelie  Torgersen            38.9           17.8   
8       13          13  Adelie  Torgersen            38.6           21.2   
9       14          14  Adelie  Torgersen            34.6           21.1   
10      15          15  Adelie  Torgersen            36.6           17.8   
..     ...         ...     ...        ...             ...            ...   
138    144         144  Adelie      Dream            37.3           16.8   
141    147         147  Adelie      Dream            36.6           18.4   
142    148         148  Adelie      Dream            36.0           17.8   
143    149         149  Adelie      Dream            37.8           18.1   
144    150         150  Adelie      Dream            36.0           17.1   

     flipper_length_mm  body_mass_g     sex  year  
3                193.0       3450.0  female  2007  
5                181.0       3625.0  female  2007  
8                191.0       3800.0    male  2007  
9                198.0       4400.0    male  2007  
10               185.0       3700.0  female  2007  
..                 ...          ...     ...   ...  
138              192.0       3000.0  female  2009  
141              184.0       3475.0  female  2009  
142              195.0       3450.0  female  2009  
143              193.0       3750.0    male  2009  
144              187.0       3700.0  female  2009  

[75 rows x 10 columns]

In [44]:
# bill length less than 39 and bill depth less than 18
shortboi2 = (DF4["bill_length_mm"] < 39) & (DF4["bill_depth_mm"] < 18)

DF4.loc[shortboi2]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
5        6           6  Adelie  Torgersen            38.9           17.8   
10      15          15  Adelie  Torgersen            36.6           17.8   
19      24          24  Adelie     Biscoe            38.8           17.2   
29      34          34  Adelie      Dream            36.4           17.0   
39      44          44  Adelie      Dream            37.0           16.9   
42      48          48  Adelie      Dream            36.0           17.9   
46      52          52  Adelie     Biscoe            35.0           17.9   
52      58          58  Adelie     Biscoe            36.5           16.6   
54      60          60  Adelie     Biscoe            35.7           16.9   
56      62          62  Adelie     Biscoe            37.6           17.0   
58      64          64  Adelie     Biscoe            36.4           17.1   
60      66          66  Adelie     Biscoe            35.5           16.2   
62      68          68  Adelie  Torgersen            35.9           16.6   
68      74          74  Adelie  Torgersen            35.5           17.5   
72      78          78  Adelie  Torgersen            36.2           16.1   
74      80          80  Adelie  Torgersen            34.6           17.2   
78      84          84  Adelie      Dream            37.3           17.8   
86      92          92  Adelie      Dream            34.0           17.1   
88      94          94  Adelie      Dream            36.2           17.3   
92      98          98  Adelie      Dream            33.1           16.1   
94     100         100  Adelie     Biscoe            35.0           17.9   
96     102         102  Adelie     Biscoe            37.7           16.0   
100    106         106  Adelie     Biscoe            38.6           17.2   
102    108         108  Adelie     Biscoe            38.1           17.0   
104    110         110  Adelie     Biscoe            38.1           16.5   
110    116         116  Adelie  Torgersen            38.6           17.0   
112    118         118  Adelie  Torgersen            35.7           17.0   
114    120         120  Adelie  Torgersen            36.2           17.2   
118    124         124  Adelie  Torgersen            35.2           15.9   
120    126         126  Adelie  Torgersen            38.8           17.6   
124    130         130  Adelie  Torgersen            38.5           17.9   
128    134         134  Adelie      Dream            38.1           17.6   
130    136         136  Adelie      Dream            35.6           17.5   
132    138         138  Adelie      Dream            37.0           16.5   
136    142         142  Adelie      Dream            32.1           15.5   
138    144         144  Adelie      Dream            37.3           16.8   
142    148         148  Adelie      Dream            36.0           17.8   
144    150         150  Adelie      Dream            36.0           17.1   

     flipper_length_mm  body_mass_g     sex  year  
5                181.0       3625.0  female  2007  
10               185.0       3700.0  female  2007  
19               180.0       3800.0    male  2007  
29               195.0       3325.0  female  2007  
39               185.0       3000.0  female  2007  
42               190.0       3450.0  female  2007  
46               190.0       3450.0  female  2008  
52               181.0       2850.0  female  2008  
54               185.0       3150.0  female  2008  
56               185.0       3600.0  female  2008  
58               184.0       2850.0  female  2008  
60               195.0       3350.0  female  2008  
62               190.0       3050.0  female  2008  
68               190.0       3700.0  female  2008  
72               187.0       3550.0  female  2008  
74               189.0       3200.0  female  2008  
78               191.0       3350.0  female  2008  
86               185.0       3400.0  female  2008  
88               187.0       3300.0  female  2008  


In [46]:
# mean body mass of short bois
DF4.loc[shortboi2, "body_mass_g"].mean()

3326.315789473684

In [47]:
# bill length less than 39 OR bill depth less than 18
shortboi3 = (DF4["bill_length_mm"] < 39) | (DF4["bill_depth_mm"] < 18)

DF4.loc[shortboi3]

index  Unnamed: 0    species     island  bill_length_mm  bill_depth_mm  \
1        1           1     Adelie  Torgersen            39.5           17.4   
3        4           4     Adelie  Torgersen            36.7           19.3   
5        6           6     Adelie  Torgersen            38.9           17.8   
7       12          12     Adelie  Torgersen            41.1           17.6   
8       13          13     Adelie  Torgersen            38.6           21.2   
..     ...         ...        ...        ...             ...            ...   
317    328          52  Chinstrap      Dream            45.7           17.3   
319    330          54  Chinstrap      Dream            42.5           17.3   
321    332          56  Chinstrap      Dream            45.2           16.6   
326    337          61  Chinstrap      Dream            46.8           16.5   
327    338          62  Chinstrap      Dream            45.7           17.0   

     flipper_length_mm  body_mass_g     sex  year  
1                186.0       3800.0  female  2007  
3                193.0       3450.0  female  2007  
5                181.0       3625.0  female  2007  
7                182.0       3200.0  female  2007  
8                191.0       3800.0    male  2007  
..                 ...          ...     ...   ...  
317              193.0       3600.0  female  2009  
319              187.0       3350.0  female  2009  
321              191.0       3250.0  female  2009  
326              189.0       3650.0  female  2009  
327              195.0       3650.0  female  2009  

[238 rows x 10 columns]

### By Column Type

In [48]:
#info
DF4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   index              333 non-null    int64  
 1   Unnamed: 0         333 non-null    int64  
 2   species            333 non-null    object 
 3   island             333 non-null    object 
 4   bill_length_mm     333 non-null    float64
 5   bill_depth_mm      333 non-null    float64
 6   flipper_length_mm  333 non-null    float64
 7   body_mass_g        333 non-null    float64
 8   sex                333 non-null    object 
 9   year               333 non-null    int64  
dtypes: float64(4), int64(3), object(3)
memory usage: 26.1+ KB


In [50]:
num = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

DF4_numeric = DF4.select_dtypes(include = num)

DF4_numeric


index  Unnamed: 0  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0           0            39.1           18.7              181.0   
1        1           1            39.5           17.4              186.0   
2        2           2            40.3           18.0              195.0   
3        4           4            36.7           19.3              193.0   
4        5           5            39.3           20.6              190.0   
..     ...         ...             ...            ...                ...   
328    339          63            55.8           19.8              207.0   
329    340          64            43.5           18.1              202.0   
330    341          65            49.6           18.2              193.0   
331    342          66            50.8           19.0              210.0   
332    343          67            50.2           18.7              198.0   

     body_mass_g  year  
0         3750.0  2007  
1         3800.0  2007  
2         3250.0  2007  
3         3450.0  2007  
4         3650.0  2007  
..           ...   ...  
328       4000.0  2009  
329       3400.0  2009  
330       3775.0  2009  
331       4100.0  2009  
332       3775.0  2009  

[333 rows x 7 columns]

### Grabbing columns by name

In [53]:
bill_vars = [columnname for columnname in DF4.columns if columnname.startswith("bill")]
bill_vars

DF4[bill_vars]

bill_length_mm  bill_depth_mm
0              39.1           18.7
1              39.5           17.4
2              40.3           18.0
3              36.7           19.3
4              39.3           20.6
..              ...            ...
328            55.8           19.8
329            43.5           18.1
330            49.6           18.2
331            50.8           19.0
332            50.2           18.7

[333 rows x 2 columns]

# Adding Data to a Data Frame

In [54]:
# bill ratio
DF4["bill_ratio"] = DF4["bill_length_mm"]/DF4["bill_depth_mm"]

In [55]:
DF4.head()

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0      0           0  Adelie  Torgersen            39.1           18.7   
1      1           1  Adelie  Torgersen            39.5           17.4   
2      2           2  Adelie  Torgersen            40.3           18.0   
3      4           4  Adelie  Torgersen            36.7           19.3   
4      5           5  Adelie  Torgersen            39.3           20.6   

   flipper_length_mm  body_mass_g     sex  year  bill_Ratio  
0              181.0       3750.0    male  2007    2.090909  
1              186.0       3800.0  female  2007    2.270115  
2              195.0       3250.0  female  2007    2.238889  
3              193.0       3450.0  female  2007    1.901554  
4              190.0       3650.0    male  2007    1.907767

# Numpy Array Operations

In [56]:
# creating 
x = np.array([1,2,3,4,5,6])

x_list = [1,2,3,4,5,6]

In [59]:
# indexing
x_list[2]

x[2]

3

In [61]:
# multiplication
x_list * 3

x * 3

array([ 3,  6,  9, 12, 15, 18])

In [62]:
y = np.array([2,2,2,2,2,2])
y_list = [2,2,2,2,2,2]

In [64]:
# addition
x_list + y_list

x + y

array([3, 4, 5, 6, 7, 8])

## Using `np` to calculate distance

$ dist = \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2 + ... + (x_n - y_n)^2}$

In [65]:
# distances
x - y

array([-1,  0,  1,  2,  3,  4])

In [66]:
(x - y)**2

array([ 1,  0,  1,  4,  9, 16])

In [67]:
np.sum((x - y)**2)

31

In [68]:
np.sqrt(np.sum((x - y)**2))

5.5677643628300215

In [69]:
# the norm way
np.linalg.norm(x-y)

5.5677643628300215

## Random Numbers

In [75]:
# normal
np.random.normal(loc = 0, scale = 1, size = 10)

array([-0.19231906,  0.27077609, -0.33359954,  0.11395876,  0.82290002,
        0.93149519,  0.04076908, -0.74608416,  0.2917224 , -3.59122675])

In [76]:
# uniform
np.random.uniform(low = 0, high = 1, size = 10)

array([0.80356966, 0.55554918, 0.1245342 , 0.84277466, 0.35866193,
       0.9490002 , 0.93425298, 0.76332564, 0.67323533, 0.54575142])

In [77]:
# choice
names = ["Chelsea", "Tony", "Julie", "Chris", "Quinn"]

np.random.choice(names)

'Julie'

In [78]:
# choice with replacement
np.random.choice(["A", "B"], size = 100, replace = True)

array(['B', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'B', 'B',
       'B', 'A', 'A', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'B',
       'A', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'A',
       'A', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'B', 'B', 'B',
       'A', 'B', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B',
       'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'B', 'B', 'A',
       'A', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'B',
       'A', 'B', 'B', 'B', 'A', 'B', 'A', 'B', 'A'], dtype='<U1')

In [81]:
# seed
np.random.seed(12393)
np.random.normal(0,1,1)

array([-0.10700052])