In [1]:
import pandas as pd
import numpy as np

# Creating a DF

In [2]:
# Make my own DF
Name = ["Tom", "Jane", "Alice"]
Age = [20, 21, 19]
Major = ["Business", "Data Analytics", "Business"]

toDF = {"Name": Name, "Age": Age, "Major": Major}

DF = pd.DataFrame(toDF)

DF.head()

Name  Age           Major
0    Tom   20        Business
1   Jane   21  Data Analytics
2  Alice   19        Business

In [3]:
# With Lists
toDF2 = [["Tom", 20, "Business"], ["Jane", 21, "Data Analytics"], ["Alice", 19, "Business"]]
DF2 = pd.DataFrame(toDF2,columns = ["Name", "Age", "Major"])

DF2.head()

Name  Age           Major
0    Tom   20        Business
1   Jane   21  Data Analytics
2  Alice   19        Business

In [4]:
# From URL
urlDF = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv"

DF3 = pd.read_csv(urlDF)

DF3.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
# From your Computer
pathDF = "/Users/chelseaparlett/Desktop/Desktop/School/CPSC392parlettpelleriti/Data/penguins.csv"
DF4 = pd.read_csv(pathDF)

DF4.head()

Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0           0  Adelie  Torgersen            39.1           18.7   
1           1  Adelie  Torgersen            39.5           17.4   
2           2  Adelie  Torgersen            40.3           18.0   
3           3  Adelie  Torgersen             NaN            NaN   
4           4  Adelie  Torgersen            36.7           19.3   

   flipper_length_mm  body_mass_g     sex  year  
0              181.0       3750.0    male  2007  
1              186.0       3800.0  female  2007  
2              195.0       3250.0  female  2007  
3                NaN          NaN     NaN  2007  
4              193.0       3450.0  female  2007

# Exploring your DF

In [6]:
# Checking out your DF
DF4.shape

(344, 9)

In [7]:
# Column names
DF4.columns

Index(['Unnamed: 0', 'species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='object')

In [8]:
# What do your columns look like?
DF4.info()
DF4.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object 
 8   year               344 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB


Unnamed: 0  bill_length_mm  bill_depth_mm  flipper_length_mm  \
count  344.000000      342.000000     342.000000         342.000000   
mean    62.151163       43.921930      17.151170         200.915205   
std     40.430199        5.459584       1.974793          14.061714   
min      0.000000       32.100000      13.100000         172.000000   
25%     28.000000       39.225000      15.600000         190.000000   
50%     57.000000       44.450000      17.300000         197.000000   
75%     94.250000       48.500000      18.700000         213.000000   
max    151.000000       59.600000      21.500000         231.000000   

       body_mass_g         year  
count   342.000000   344.000000  
mean   4201.754386  2008.029070  
std     801.954536     0.818356  
min    2700.000000  2007.000000  
25%    3550.000000  2007.000000  
50%    4050.000000  2008.000000  
75%    4750.000000  2009.000000  
max    6300.000000  2009.000000

In [9]:
DF4.head(12)

Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0            0  Adelie  Torgersen            39.1           18.7   
1            1  Adelie  Torgersen            39.5           17.4   
2            2  Adelie  Torgersen            40.3           18.0   
3            3  Adelie  Torgersen             NaN            NaN   
4            4  Adelie  Torgersen            36.7           19.3   
5            5  Adelie  Torgersen            39.3           20.6   
6            6  Adelie  Torgersen            38.9           17.8   
7            7  Adelie  Torgersen            39.2           19.6   
8            8  Adelie  Torgersen            34.1           18.1   
9            9  Adelie  Torgersen            42.0           20.2   
10          10  Adelie  Torgersen            37.8           17.1   
11          11  Adelie  Torgersen            37.8           17.3   

    flipper_length_mm  body_mass_g     sex  year  
0               181.0       3750.0    male  2007  
1               186.0       3800.0  female  2007  
2               195.0       3250.0  female  2007  
3                 NaN          NaN     NaN  2007  
4               193.0       3450.0  female  2007  
5               190.0       3650.0    male  2007  
6               181.0       3625.0  female  2007  
7               195.0       4675.0    male  2007  
8               193.0       3475.0     NaN  2007  
9               190.0       4250.0     NaN  2007  
10              186.0       3300.0     NaN  2007  
11              180.0       3700.0     NaN  2007

## groupby()

In [10]:
# use groupby to get species average bill length
DF4.groupby(["species"])["bill_length_mm"].mean()

species
Adelie       38.791391
Chinstrap    48.833824
Gentoo       47.504878
Name: bill_length_mm, dtype: float64

## Grabbing columns by name

In [11]:
bill_vars = [colname for colname in DF4.columns if colname.startswith("bill")]
bill_vars

['bill_length_mm', 'bill_depth_mm']

## Dropping Missing Data

In [12]:
# Check for missing values
DF4.isnull().sum()

Unnamed: 0            0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [13]:
DF4 = DF4.dropna()
DF4.isnull().sum()

Unnamed: 0           0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [14]:
# another way to drop your data
DF4.dropna(inplace = True)
DF4.reset_index(inplace = True)

## Creating Dummy Variables
### A single dummy variable

In [15]:
# simulate data
np.random.seed(8675309)

n = 100
x1 = np.random.choice(["A", "B", "C"], n)
x2 = np.random.normal(0,1,n)

df = pd.DataFrame({"group":x1, "happiness": x2})

df.head()

group  happiness
0     B  -0.998062
1     A   1.152839
2     A   0.193641
3     A   0.356045
4     A  -1.046417

In [16]:
# notice that the categorical variable `group`, has more than 2 categories.

# many algorithms want dummy/binary variables, so let's turn `group` into dummy/binary variables!
dummies = pd.get_dummies(df, columns = ["group"])

# you can see that we now have 3 columns, A, B, and C that
# are all binary variables indicating whether each person was
# A (1-yes, 0-no), B (1-yes, 0-no), or C (1-yes, 0-no)
print(dummies)

    happiness  group_A  group_B  group_C
0   -0.998062        0        1        0
1    1.152839        1        0        0
2    0.193641        1        0        0
3    0.356045        1        0        0
4   -1.046417        1        0        0
..        ...      ...      ...      ...
95   0.251880        0        1        0
96  -0.940828        0        0        1
97   1.012550        0        1        0
98   0.778642        0        1        0
99  -2.165909        1        0        0

[100 rows x 4 columns]


### Multiple dummy variables

In [17]:
np.random.seed(8675309)

n = 100
letter_grade = np.random.choice(["A", "B", "C", "D", "F"], n)
class_level = np.random.choice(["Freshman", "Sophomore", "Junior", "Senior"], n)
x2 = np.random.normal(0,1,n)

df = pd.DataFrame({"Grade":letter_grade, "Class": class_level, "happiness": x2})

df.head()

Grade      Class  happiness
0     B  Sophomore   0.629483
1     F   Freshman   2.109350
2     F   Freshman  -1.292751
3     A  Sophomore  -0.020285
4     A     Senior   0.735859

In [18]:
df = pd.get_dummies(df, columns = ["Grade", "Class"])

df.head()

happiness  Grade_A  Grade_B  Grade_C  Grade_D  Grade_F  Class_Freshman  \
0   0.629483        0        1        0        0        0               0   
1   2.109350        0        0        0        0        1               1   
2  -1.292751        0        0        0        0        1               1   
3  -0.020285        1        0        0        0        0               0   
4   0.735859        1        0        0        0        0               0   

   Class_Junior  Class_Senior  Class_Sophomore  
0             0             0                1  
1             0             0                0  
2             0             0                0  
3             0             0                1  
4             0             1                0

# Grabbing Subsets of Data

## By Column Name

In [19]:
# Pulling certain rows/columns/sets
DF4["species"]

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...    
328    Chinstrap
329    Chinstrap
330    Chinstrap
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: object

In [20]:
DF4["bill_length_mm"].mean()

43.9927927927928

## By Index

In [21]:
DF4.iloc[8]

index                       13
Unnamed: 0                  13
species                 Adelie
island               Torgersen
bill_length_mm            38.6
bill_depth_mm             21.2
flipper_length_mm          191
body_mass_g               3800
sex                       male
year                      2007
Name: 8, dtype: object

In [22]:
#9th row
DF4.iloc[[8]]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
8     13          13  Adelie  Torgersen            38.6           21.2   

   flipper_length_mm  body_mass_g   sex  year  
8              191.0       3800.0  male  2007

In [23]:
#3-7 row
DF4.iloc[2:7]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
2      2           2  Adelie  Torgersen            40.3           18.0   
3      4           4  Adelie  Torgersen            36.7           19.3   
4      5           5  Adelie  Torgersen            39.3           20.6   
5      6           6  Adelie  Torgersen            38.9           17.8   
6      7           7  Adelie  Torgersen            39.2           19.6   

   flipper_length_mm  body_mass_g     sex  year  
2              195.0       3250.0  female  2007  
3              193.0       3450.0  female  2007  
4              190.0       3650.0    male  2007  
5              181.0       3625.0  female  2007  
6              195.0       4675.0    male  2007

## By Condition (Booleans)

In [24]:
torg = DF4["island"] == "Torgersen"
DF4.loc[torg].head()

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0      0           0  Adelie  Torgersen            39.1           18.7   
1      1           1  Adelie  Torgersen            39.5           17.4   
2      2           2  Adelie  Torgersen            40.3           18.0   
3      4           4  Adelie  Torgersen            36.7           19.3   
4      5           5  Adelie  Torgersen            39.3           20.6   

   flipper_length_mm  body_mass_g     sex  year  
0              181.0       3750.0    male  2007  
1              186.0       3800.0  female  2007  
2              195.0       3250.0  female  2007  
3              193.0       3450.0  female  2007  
4              190.0       3650.0    male  2007

In [25]:
shortboi = DF4["bill_length_mm"] < 39

DF4.loc[shortboi]

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
3        4           4  Adelie  Torgersen            36.7           19.3   
5        6           6  Adelie  Torgersen            38.9           17.8   
8       13          13  Adelie  Torgersen            38.6           21.2   
9       14          14  Adelie  Torgersen            34.6           21.1   
10      15          15  Adelie  Torgersen            36.6           17.8   
..     ...         ...     ...        ...             ...            ...   
138    144         144  Adelie      Dream            37.3           16.8   
141    147         147  Adelie      Dream            36.6           18.4   
142    148         148  Adelie      Dream            36.0           17.8   
143    149         149  Adelie      Dream            37.8           18.1   
144    150         150  Adelie      Dream            36.0           17.1   

     flipper_length_mm  body_mass_g     sex  year  
3                193.0       3450.0  female  2007  
5                181.0       3625.0  female  2007  
8                191.0       3800.0    male  2007  
9                198.0       4400.0    male  2007  
10               185.0       3700.0  female  2007  
..                 ...          ...     ...   ...  
138              192.0       3000.0  female  2009  
141              184.0       3475.0  female  2009  
142              195.0       3450.0  female  2009  
143              193.0       3750.0    male  2009  
144              187.0       3700.0  female  2009  

[75 rows x 10 columns]

In [26]:
shortboi2 = (DF4["bill_length_mm"] < 39) & (DF4["bill_depth_mm"] < 18)

DF4.loc[shortboi2].head()

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
5       6           6  Adelie  Torgersen            38.9           17.8   
10     15          15  Adelie  Torgersen            36.6           17.8   
19     24          24  Adelie     Biscoe            38.8           17.2   
29     34          34  Adelie      Dream            36.4           17.0   
39     44          44  Adelie      Dream            37.0           16.9   

    flipper_length_mm  body_mass_g     sex  year  
5               181.0       3625.0  female  2007  
10              185.0       3700.0  female  2007  
19              180.0       3800.0    male  2007  
29              195.0       3325.0  female  2007  
39              185.0       3000.0  female  2007

In [27]:
DF4.loc[shortboi2, "body_mass_g"].mean()

3326.315789473684

In [28]:
shortboi2 = (DF4["bill_length_mm"] < 39) | (DF4["bill_depth_mm"] < 18)

DF4.loc[shortboi2].head()

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
1      1           1  Adelie  Torgersen            39.5           17.4   
3      4           4  Adelie  Torgersen            36.7           19.3   
5      6           6  Adelie  Torgersen            38.9           17.8   
7     12          12  Adelie  Torgersen            41.1           17.6   
8     13          13  Adelie  Torgersen            38.6           21.2   

   flipper_length_mm  body_mass_g     sex  year  
1              186.0       3800.0  female  2007  
3              193.0       3450.0  female  2007  
5              181.0       3625.0  female  2007  
7              182.0       3200.0  female  2007  
8              191.0       3800.0    male  2007

### By Column Type

In [29]:
DF4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   index              333 non-null    int64  
 1   Unnamed: 0         333 non-null    int64  
 2   species            333 non-null    object 
 3   island             333 non-null    object 
 4   bill_length_mm     333 non-null    float64
 5   bill_depth_mm      333 non-null    float64
 6   flipper_length_mm  333 non-null    float64
 7   body_mass_g        333 non-null    float64
 8   sex                333 non-null    object 
 9   year               333 non-null    int64  
dtypes: float64(4), int64(3), object(3)
memory usage: 26.1+ KB


In [30]:
num = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

DF4_numeric = DF4.select_dtypes(include=num)

# Adding Data to a Data Frame

In [31]:
DF4["billRatio"] = DF4.bill_length_mm/DF4.bill_depth_mm

In [32]:
DF4.head()

index  Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0      0           0  Adelie  Torgersen            39.1           18.7   
1      1           1  Adelie  Torgersen            39.5           17.4   
2      2           2  Adelie  Torgersen            40.3           18.0   
3      4           4  Adelie  Torgersen            36.7           19.3   
4      5           5  Adelie  Torgersen            39.3           20.6   

   flipper_length_mm  body_mass_g     sex  year  billRatio  
0              181.0       3750.0    male  2007   2.090909  
1              186.0       3800.0  female  2007   2.270115  
2              195.0       3250.0  female  2007   2.238889  
3              193.0       3450.0  female  2007   1.901554  
4              190.0       3650.0    male  2007   1.907767

# Numpy Vector Operations

In [33]:
x = np.array([1,2,3,4,5,6])
x_list = [1,2,3,4,5,6]

In [34]:
x[2]

3

In [35]:
x_list[2]

3

In [36]:
x*3

array([ 3,  6,  9, 12, 15, 18])

In [37]:
x_list*3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [38]:
y = np.array([2,2,2,2,2,2])
y_list = [2,2,2,2,2,2]

In [39]:
x + y

array([3, 4, 5, 6, 7, 8])

In [40]:
x_list + y_list

[1, 2, 3, 4, 5, 6, 2, 2, 2, 2, 2, 2]

## Using `np` to calculate distance

In [41]:
# distances
x - y

array([-1,  0,  1,  2,  3,  4])

In [42]:
(x-y)**2

array([ 1,  0,  1,  4,  9, 16])

In [43]:
np.sum((x-y)**2)

31

In [44]:
np.sqrt(np.sum((x-y)**2))

5.5677643628300215

In [45]:
# the norm way
np.linalg.norm(x-y)

5.5677643628300215

## Random Numbers

In [46]:
np.random.normal(loc = 0,scale = 1, size = 10)

array([ 1.25664584,  1.60299628, -0.02572116,  0.49999157,  1.28782204,
        0.23522165, -0.72680735, -3.02387235,  0.71492412, -1.26904115])

In [47]:
np.random.choice(["Chelsea", "Tony", "Julie", "Chris", "Quinn"])

'Chelsea'

In [48]:
np.random.uniform(low = 0, high = 1, size = 10)

array([0.73640482, 0.7127012 , 0.47904714, 0.93373901, 0.44879873,
       0.88103047, 0.77162477, 0.10020401, 0.58178108, 0.16743006])

In [49]:
np.random.choice(["A","B"], size = 100, replace = True)

array(['B', 'A', 'B', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'B', 'A',
       'A', 'A', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A',
       'A', 'B', 'B', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'B',
       'A', 'B', 'B', 'A', 'B', 'B', 'B', 'A', 'B', 'A', 'A', 'A', 'B',
       'A', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'A', 'A', 'B',
       'A', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B',
       'A', 'B', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'B',
       'B', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'B'], dtype='<U1')

In [50]:
np.random.seed(1234)
np.random.normal(0,1,1)

array([0.47143516])